# opendatacon version 1.8.0-RC6
## 1.8.0-RC6
  * New Port type added: FileTransferPort - for transferring files via OctetString data type
  * DNP3 Ports and JSON Port support for OctetString
  * Bugfixes for PythonPort, and more examples
  * SimPort UI features - std dev scaling, abs analog toggle, reset start vals
  * DNP3 Analog control bugfixes
  * i386 packages now built on Debian Bookworm

diff --git a/.github/workflows/opendatacon.yml b/.github/workflows/opendatacon.yml
--- a/.github/workflows/opendatacon.yml
+++ b/.github/workflows/opendatacon.yml
@@ -52,8 +52,9 @@ jobs:
     
     - if: always()
       name: Set log level
+      shell: bash
       run: |
-        [ ${{ runner.debug }} = 1 ] && echo 'LOG_LVL=debug' || echo 'LOG_LVL=error' >> $GITHUB_ENV
+        [ ${{ runner.debug }} ] && echo 'LOG_LVL=debug' || echo 'LOG_LVL=error' >> $GITHUB_ENV
 
     - uses: actions/checkout@v2
       with:
@@ -224,8 +225,9 @@ jobs:
     
     - if: always()
       name: Set log level
+      shell: bash
       run: |
-        [ ${{ runner.debug }} = 1 ] && echo 'LOG_LVL=debug' || echo 'LOG_LVL=error' >> $GITHUB_ENV
+        [ ${{ runner.debug }} ] && echo 'LOG_LVL=debug' || echo 'LOG_LVL=error' >> $GITHUB_ENV
         
     - name: Start run wrapper
       run: echo '#!/bin/bash' >> $HOME/run.sh
